version: "3.9"

services:
  users-svc:
    build:
      context: "."
    networks:
      - "users-svc"
    ports:
      - "5000:5000"
    volumes: 
      - .:/usr/src/app/:rw
    depends_on:
      db:
        condition: service_healthy
    environment: 
      # because we are in the docker network
      - TYPEORM_HOST=db
      - POSTGRES_HOST=db
    env_file:
      - .env

  db:
    image: postgres
    networks:
      - "users-svc"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - pgadmin:/data/root/.pgadmin
    env_file:
    - .env
    networks:
    - "users-svc"
  
  # Example how to support different databases
  # Note we should follow one database per service when using microservices
  # mongodb:
  #   image: mongo:latest
  #   environment:
  #     MONGODB_INITDB_DATABASE: "test"
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     # creates a volume called 'mongo' on your disk and maps the /data/db
  #     - mongo:/data/db

volumes: 
  # mongo:
  db:
  pgadmin:

networks:
  users-svc: